spring:
  application:
    name: generate
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8081
rocketmq:
  name-server: localhost:9876  # RocketMQ NameServer 地址
  producer:
    group: springboot-producer-group # 生产者组
  consumer:
    group: springboot-consumer-group # 消费者组
    topic: TopicTest # 订阅的主题